/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui").default || require("daisyui")],
  safelist: [
    // DaisyUI component classes - use patterns to ensure they're not purged
    { pattern: /btn/ },
    { pattern: /btn-primary/ },
    { pattern: /btn-outline/ },
    { pattern: /card/ },
    { pattern: /badge/ },
    { pattern: /modal/ },
    { pattern: /dropdown/ },
    { pattern: /loading/ },
    { pattern: /alert/ },
    { pattern: /form-control/ },
    { pattern: /label/ },
    { pattern: /input/ },
    { pattern: /select/ },
    { pattern: /table/ },
    { pattern: /avatar/ },
    { pattern: /menu/ },
    // Base colors
    { pattern: /bg-base-(100|200|300)/ },
    { pattern: /text-base-content/ },
    { pattern: /border-base-(100|200|300)/ },
  ],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#432AD5",
          secondary: "#432AD5",
          accent: "#432AD5",
          neutral: "#3d4451",
          "base-100": "#ffffff",
          "base-200": "#f5f5f5",
          "base-300": "#e5e5e5",
          info: "#432AD5",
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
      },
      {
        dark: {
          primary: "#432AD5",
          secondary: "#432AD5",
          accent: "#432AD5",
          neutral: "#1a1a1a",
          "base-100": "#1a1a1a",
          "base-200": "#2a2a2a",
          "base-300": "#3a3a3a",
          info: "#432AD5",
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: "html",
  },
};
